# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Catrione Lee
tagline:          'M.Sc. Candidate in Bioinformatics and AMR'
description:      'M.Sc. Candidate in Bioinformatics and AMR'
url:              https://catrionelee.github.io/
baseurl:          /

author:
  name:           'Catrione Lee'
  url:            https://twitter.com/CatrioneLee

paginate:         5

# Custom vars
version:          2.1.0

#github:
  #repo:           https://github.com/poole/hyde
