# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Catrione Lee
tagline:          ''
description:      'M.Sc. Candidate in Bioinformatics and AMR'
url:              http://catrionelee.github.io
baseurl:          /

author:
  name:           'Catrione Lee'
  url:            https://twitter.com/CatrioneLee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/catrionelee/catrionelee.github.io
