# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Catrione Lee-Rocca'
tagline:          'Ph.D. Student in Protein Evolutionary Biology'
description:      'Personal webpage of Catrione Lee-Rocca. A Ph.D. student studying whale hemoglobin from a mostly land-locked province.'
url:              https://catrionelee.github.io
#baseurl:          /

author:           catrionelee
  name:           'Catrione Lee'
  url:            

plugins: 
  - jekyll-paginate

paginate:         6


# Custom vars
version:          2.1.0

#github:
  #repo:           https://github.com/poole/hyde
