# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Catrione Lee
tagline:          'M.Sc. Candidate in Bioinformatics and AMR'
description:      'M.Sc. Candidate in Bioinformatics and AMR'
url:              https://catrionelee.github.io
#baseurl:          /

author:
  name:           'Catrione Lee'
  url:            https://twitter.com/CatrioneLee

plugins: 
  - jekyll-paginate

paginate:         4

# Custom vars
version:          2.1.0

#github:
  #repo:           https://github.com/poole/hyde
